import Link from "next/link";
import { SITE, pageMeta, breadcrumbJsonLd } from "@/lib/site";

export const metadata = pageMeta({
  title: "Terms of Service",
  description:
    "The rules for using YATools: fair use, no abuse or automated scraping, outputs provided as-is, and your responsibility for content you process.",
  path: "/terms",
  keywords: ["yatools terms", "terms of service", "fair use"],
});

const crumbs = [
  { name: "Home", path: "/" },
  { name: "Terms", path: "/terms" },
];

function JsonLd({ data }: { data: unknown }) {
  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(data) }}
    />
  );
}

function Crumbs({ items }: { items: { name: string; path: string }[] }) {
  return (
    <nav aria-label="Breadcrumb" className="mb-6">
      <ol
        className="font-mono2 m-0 flex flex-wrap items-center gap-2 p-0 text-xs"
        style={{ listStyle: "none" }}
      >
        {items.map((item, i) => (
          <li key={item.path} className="flex items-center gap-2">
            {i > 0 && (
              <span aria-hidden="true" style={{ color: "var(--muted)" }}>
                /
              </span>
            )}
            {i === items.length - 1 ? (
              <span aria-current="page" style={{ color: "var(--text)" }}>
                {item.name}
              </span>
            ) : (
              <Link
                href={item.path}
                className="no-underline hover:underline"
                style={{ color: "var(--muted)" }}
              >
                {item.name}
              </Link>
            )}
          </li>
        ))}
      </ol>
    </nav>
  );
}

export default function Page() {
  return (
    <>
      <JsonLd data={breadcrumbJsonLd(crumbs)} />
      <div className="wrap py-10 md:py-14">
        <Crumbs items={crumbs} />
        <div className="max-w-3xl">
          <p className="eyebrow mt-6">
            <span className="dot" /> Legal
          </p>
          <h1 className="hero-title mt-4">
            Terms of <em>service</em>
          </h1>
          <p className="sec-sub mt-4 text-lg">
            The short version: use the tools fairly, don&apos;t abuse them,
            and understand they come with no guarantees. Last updated:
            2026-10-05.
          </p>
        </div>

        <div className="prose-neu max-w-3xl mt-10">
          <h2>The service</h2>
          <p>
            YATools provides free online tools and a free developer API. Usage
            is subject to <Link href="/developers/rate-limits">fair-use quotas</Link>{" "}
            so the service stays available for everyone. We may change,
            limit, or discontinue any tool at any time.
          </p>

          <h2>Acceptable use</h2>
          <p>You agree not to:</p>
          <ul>
            <li>
              Abuse the service — including automated scraping, bot-driven
              request loops, or attempts to bypass rate limits.
            </li>
            <li>
              Process unlawful content, or content that infringes anyone
              else&apos;s rights.
            </li>
            <li>
              Resell API access as your own service, or present YATools
              outputs as someone else&apos;s work in a misleading way.
            </li>
            <li>
              Interfere with the service&apos;s operation or probe it for
              vulnerabilities. Found a security issue?{" "}
              <Link href="/contact">Tell us</Link> instead.
            </li>
          </ul>
          <p>
            IPs or patterns that violate these rules may be rate-limited or
            blocked without notice.
          </p>

          <h2>Your content</h2>
          <p>
            You must have the rights to any content you process with our tools
            — the URLs you screenshot, the audio you transcribe, the text you
            convert. You&apos;re responsible for what you upload and what you
            do with the outputs.
          </p>

          <h2>Generated audio (TTS) — personal, non-commercial use</h2>
          <p>
            Audio generated by the Text to Speech tool is provided for{" "}
            <strong>personal, non-commercial use</strong>: your own videos,
            study material, accessibility needs, and creative projects. You may
            not use generated voices in paid advertising, sell them as a
            voice-over service, or present them as a real person&apos;s
            recording. For any commercial use of generated audio,{" "}
            <a href={`mailto:${SITE.email}`}>ask us first</a>.
          </p>

          <h2>Outputs are provided as-is</h2>
          <p>
            Transcriptions can contain errors, AI voices can mispronounce
            words, screenshots depend on the live page at capture time. Tools
            are provided <strong>as-is, with no warranty</strong> of accuracy,
            availability, or fitness for any particular purpose. Always verify
            important outputs before relying on them.
          </p>

          <h2>Limitation of liability</h2>
          <p>
            To the maximum extent permitted by law, YATools and its owner are
            not liable for any direct or indirect damages arising from your use
            of the service — including reliance on inaccurate outputs.
          </p>

          <h2>Changes</h2>
          <p>
            We may update these terms; the date at the top will change when we
            do. Continued use of the service after changes means you accept the
            updated terms. Questions? Email{" "}
            <a href={`mailto:${SITE.email}`}>{SITE.email}</a>.
          </p>
        </div>
      </div>
    </>
  );
}
